project:
  type: website
  output-dir: docs
  resources:
    - files/

website:
  search: false
  title: "30 Day Chart Challenge"


  navbar:
    background: "#cfe1ed"
    left:
      - text: Home
        href: index.qmd
      - text: Week 1
        href: qmd/week1.qmd
      - text: Week 2
        href: qmd/week1.qmd
      - text: Week 3
        href: qmd/week1.qmd
      - text: Week 4
        href: qmd/week1.qmd
    right:
      - icon: github
        href: https://github.com/natanast
        aria-label: GitHub
        

  page-footer: 
    border: true
    left: "This page is built with ❤️, [Quarto](https://quarto.org/) and is licensed under [**CC BY-SA 4.0**](http://creativecommons.org/licenses/by-sa/4.0/)."
    right: "© 2025 Natasa Anastasiadou."


format:
  html:
    css: sass/style.css
    toc: false
    minimal: false
    smooth-scroll: true
    theme: 
      light: sass/theme-light.scss
      dark:  sass/theme-dark.scss
    toggle: true

editor: visual
